<?php
if (!defined('ABSPATH')) exit;
final class WPFI_Importer {
 private $logger; public function __construct($logger){$this->logger=$logger;}
 public function import(array $feed){ if (($feed['format']??'xml')==='csv') return $this->import_csv($feed); return $this->import_xml($feed); }
 private function request($feed){$url=$this->authenticated_url($feed);$r=wp_remote_get($url,['timeout'=>120,'redirection'=>3,'user-agent'=>'WPFI/'.WPFI_VERSION,'headers'=>$this->auth_headers($feed)]);if(is_wp_error($r)){ $this->logger->write($feed,'error',$r->get_error_message());return false;} $status=wp_remote_retrieve_response_code($r);if($status<200||$status>=300){$this->logger->write($feed,'error','Feed returned HTTP '.$status);return false;}return wp_remote_retrieve_body($r);}
 private function import_csv($feed){$body=$this->request($feed);if($body===false)return false;$cfg=wp_parse_args($feed['csv']??[],['delimiter'=>',','enclosure'=>'"','has_header'=>1,'encoding'=>'UTF-8']);$delimiter=substr((string)$cfg['delimiter'],0,1)?:',';$enclosure=substr((string)$cfg['enclosure'],0,1)?:'"';$tmp=tmpfile();if(!$tmp){$this->logger->write($feed,'error','Unable to create temporary CSV file.');return false;}fwrite($tmp,$body);rewind($tmp);$headers=[];$products=0;$line=0;while(($row=fgetcsv($tmp,0,$delimiter,$enclosure))!==false){$line++;if($line===1&&!empty($cfg['has_header'])){$headers=array_map('trim',$row);continue;}if(!$headers){$headers=array_keys($feed['map']??[]);}$record=[];foreach($row as $i=>$value){$key=$headers[$i]??(string)$i;$record[$key]=trim((string)$value);}$values=[];foreach((array)($feed['map']??[]) as $field=>$column)$values[$field]=$record[(string)$column]??'';if(!$this->save_product($feed,$values))continue;$products++;}fclose($tmp);$this->logger->write($feed,'info',sprintf('CSV import completed: %d products.',$products));return true;}
 private function import_xml($feed){$body=$this->request($feed);if($body===false)return false;libxml_use_internal_errors(true);$xml=simplexml_load_string($body,'SimpleXMLElement',LIBXML_NOCDATA);if(!$xml){$this->logger->write($feed,'error','The feed is not valid XML.');return false;}foreach((array)($feed['namespaces']??[]) as $p=>$uri)$xml->registerXPathNamespace($p,$uri);$nodes=$xml->xpath($feed['product_xpath']?:'/products/product');if(!is_array($nodes)){$this->logger->write($feed,'warning','No XML product nodes matched the configured XPath.');return false;}$products=0;$variations=0;foreach($nodes as $node){$values=$this->values($node,$feed['map']??[]);if(!$this->save_product($feed,$values,$node))continue;$products++;if(!empty($feed['variation_xpath']))foreach((array)$node->xpath($feed['variation_xpath']) as $vn)if($this->save_variation($values,$vn,$feed))$variations++;}$this->logger->write($feed,'info',sprintf('XML import completed: %d products and %d variations.',$products,$variations));return true;}
 private function save_product($feed,$values,$node=null){$field=$feed['identifier_field']??'sku';$id=trim((string)($values[$field]??($values['sku']??'')));if(!$id){$this->logger->write($feed,'warning','Skipped a row without an identifier.');return false;}$existing=$field==='sku'?wc_get_product_id_by_sku($id):$this->find_meta_product($field,$id);$variable=!empty($feed['variation_xpath']);$p=$existing?wc_get_product($existing):($variable?new WC_Product_Variable():new WC_Product_Simple());if(!$p)$p=$variable?new WC_Product_Variable():new WC_Product_Simple();$this->apply_values($p,$values,$id);$pid=$p->save();if($node)$this->apply_attributes($pid,$node,$feed['attributes']??[]);elseif(!empty($feed['attributes']))$this->apply_csv_attributes($pid,$values,$feed['attributes']);if(!empty($values['category']))wp_set_object_terms($pid,array_filter(array_map('trim',preg_split('/[,|]/',(string)$values['category']))),'product_cat',false);if(!empty($values['image'])&&!has_post_thumbnail($pid))$this->image($pid,$values['image']);return true;}
 private function save_variation($parent_values,$node,$feed){$values=$this->values($node,$feed['map']??[]);$field=$feed['variation_identifier_field']??'sku';$id=trim((string)($values[$field]??($values['sku']??'')));if(!$id)return false;$vid=wc_get_product_id_by_sku($id);$p=$vid?wc_get_product($vid):new WC_Product_Variation();$p->set_parent_id($this->find_meta_product('sku',$parent_values['sku']??''));$p->set_sku($id);$this->apply_values($p,$values,$id);$p->save();return true;}
 private function values($node,$map){$v=[];foreach((array)$map as $k=>$s)$v[$k]=$this->value($node,$s);return $v;}
 private function value($node,$s){if(!$s)return '';if(strpos($s,'/')!==false||strpos($s,'@')!==false||strpos($s,'[')!==false){$r=$node->xpath($s);return is_array($r)?trim((string)($r[0]??'')):'';}$c=$node;foreach(explode('.',$s) as $p){if(!isset($c->{$p}))return '';$c=$c->{$p};}return trim((string)$c);}
 private function apply_values($p,$v,$id){$p->set_name($v['name']??$id);$p->set_sku($id);if(isset($v['description']))$p->set_description(wp_kses_post($v['description']));if(isset($v['short_description']))$p->set_short_description(wp_kses_post($v['short_description']));if(isset($v['price'])&&$v['price']!==''){$x=(string)(float)$v['price'];$p->set_regular_price($x);$p->set_price($x);}if(isset($v['sale_price'])&&$v['sale_price']!=='')$p->set_sale_price((string)(float)$v['sale_price']);if(isset($v['stock_quantity'])&&$v['stock_quantity']!==''){$stock=strtolower((string)$v['stock_quantity']);if(is_numeric($stock)){$p->set_manage_stock(true);$p->set_stock_quantity((int)$stock);$p->set_stock_status((int)$stock>0?'instock':'outofstock');}elseif($stock==='yes')$p->set_stock_status('instock');else $p->set_stock_status(in_array($stock,['outofstock','onbackorder'],true)?$stock:'instock');}}
 private function find_meta_product($f,$v){$x=get_posts(['post_type'=>'product','post_status'=>'any','posts_per_page'=>1,'meta_key'=>'_'.sanitize_key($f),'meta_value'=>$v,'fields'=>'ids']);return $x?(int)$x[0]:0;}
 private function taxonomy($n){$t='pa_'.sanitize_title($n);if(!taxonomy_exists($t))register_taxonomy($t,'product',['public'=>false,'show_ui'=>false,'rewrite'=>false]);return $t;}
 private function apply_attributes($id,$n,$a){foreach((array)$a as $name=>$s){$v=$this->value($n,$s);if($v!=='')wp_set_object_terms($id,array_filter(array_map('trim',explode('|',$v))),$this->taxonomy($name),false);}}
 private function apply_csv_attributes($id,$values,$a){foreach((array)$a as $name=>$column){$v=$values[$column]??'';if($v!=='')wp_set_object_terms($id,array_filter(array_map('trim',explode('|',$v))),$this->taxonomy($name),false);}}
 private function image($id,$url){require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/image.php';$attachment=media_sideload_image(esc_url_raw($url),$id,'','id');if(!is_wp_error($attachment)&&$attachment)set_post_thumbnail($id,$attachment);}
 private function authenticated_url($feed){$a=$feed['auth']??[];$params=is_array($a['query_params']??null)?$a['query_params']:[];return $params?add_query_arg(array_map('strval',$params),$feed['url']):$feed['url'];}
 private function auth_headers($feed){$a=$feed['auth']??[];$h=[];$type=$a['type']??'none';if($type==='api_key'&&!empty($a['api_key']))$h[$a['api_key_name']??'X-API-Key']=$a['api_key'];if($type==='bearer'&&!empty($a['bearer_token']))$h['Authorization']='Bearer '.trim($a['bearer_token']);if($type==='basic')$h['Authorization']='Basic '.base64_encode(($a['username']??'').':'.($a['password']??''));if($type==='custom')foreach((array)($a['headers']??[]) as $k=>$v)$h[$k]=$v;return $h;}
}
