<?php
if (!defined('ABSPATH')) exit;
final class WPFI_Importer {
 private $logger; public function __construct($logger){$this->logger=$logger;}
 public function import(array $feed){if(!class_exists('WooCommerce')){$this->logger->write($feed,'error','WooCommerce is not active.');return false;}$url=$this->authenticated_url($feed);$args=['timeout'=>90,'redirection'=>3,'user-agent'=>'WPFI/'.WPFI_VERSION,'headers'=>$this->auth_headers($feed)];$r=wp_remote_get($url,$args);if(is_wp_error($r)){$this->logger->write($feed,'error',$r->get_error_message());return false;}$status=wp_remote_retrieve_response_code($r);if($status<200||$status>=300){$this->logger->write($feed,'error','Feed returned HTTP '.$status);return false;}libxml_use_internal_errors(true);$xml=simplexml_load_string(wp_remote_retrieve_body($r),'SimpleXMLElement',LIBXML_NOCDATA);if(!$xml){$this->logger->write($feed,'error','The feed is not valid XML.');return false;}foreach((array)($feed['namespaces']??[]) as $p=>$uri)$xml->registerXPathNamespace($p,$uri);$nodes=$xml->xpath($feed['product_xpath']?:'/products/product');if(!is_array($nodes)){$this->logger->write($feed,'warning','No product nodes matched the configured XPath.');return false;}$products=0;$variations=0;foreach($nodes as $node){$values=$this->values($node,$feed['map']??[]);$field=$feed['identifier_field']??'sku';$id=trim((string)($values[$field]??($values['sku']??'')));if(!$id)continue;$existing=$field==='sku'?wc_get_product_id_by_sku($id):$this->find_meta_product($field,$id);$variable=!empty($feed['variation_xpath']);$p=$existing?wc_get_product($existing):($variable?new WC_Product_Variable():new WC_Product_Simple());if(!$p)$p=$variable?new WC_Product_Variable():new WC_Product_Simple();$this->apply_values($p,$values,$id);$pid=$p->save();$this->apply_attributes($pid,$node,$feed['attributes']??[]);if($variable){$p=wc_get_product($pid);$p->set_attributes($this->variation_attributes($node,$feed['attributes']??[]));$p->save();foreach((array)$node->xpath($feed['variation_xpath']) as $vn)if($this->save_variation($pid,$vn,$feed))$variations++;}$products++;}$this->logger->write($feed,'info',sprintf('Import completed: %d products and %d variations.',$products,$variations));return true;}
 private function authenticated_url($feed){$a=$feed['auth']??[];$params=is_array($a['query_params']??null)?$a['query_params']:[];return $params?add_query_arg(array_map('strval',$params),$feed['url']):$feed['url'];}
 private function auth_headers($feed){$a=$feed['auth']??[];$h=[];$type=$a['type']??'none';if($type==='api_key'&&!empty($a['api_key']))$h[sanitize_text_field($a['api_key_name']??'X-API-Key')]=sanitize_text_field($a['api_key']);if($type==='bearer'&&!empty($a['bearer_token']))$h['Authorization']='Bearer '.trim($a['bearer_token']);if($type==='basic'&&isset($a['username']))$h['Authorization']='Basic '.base64_encode($a['username'].':'.($a['password']??''));if($type==='custom')foreach((array)($a['headers']??[]) as $k=>$v)if($k!==''&&$v!=='')$h[sanitize_text_field($k)]=sanitize_text_field($v);return $h;}
 private function values($n,$m){$v=[];foreach((array)$m as $k=>$s)$v[$k]=$this->value($n,$s);return $v;}
 private function value($n,$s){if(!$s)return '';if(strpos($s,'/')!==false||strpos($s,'@')!==false||strpos($s,'[')!==false){$r=$n->xpath($s);return is_array($r)?trim((string)($r[0]??'')):'';}$c=$n;foreach(explode('.',$s) as $p){if(!isset($c->{$p}))return '';$c=$c->{$p};}return trim((string)$c);}
 private function apply_values($p,$v,$id){$p->set_name($v['name']??$id);$p->set_sku($id);if(isset($v['description']))$p->set_description(wp_kses_post($v['description']));if(isset($v['short_description']))$p->set_short_description(wp_kses_post($v['short_description']));if(isset($v['price'])&&$v['price']!==''){$x=(string)(float)$v['price'];$p->set_regular_price($x);$p->set_price($x);}if(isset($v['sale_price'])&&$v['sale_price']!=='')$p->set_sale_price((string)(float)$v['sale_price']);if(isset($v['stock_quantity'])&&$v['stock_quantity']!==''){$p->set_manage_stock(true);$p->set_stock_quantity((int)$v['stock_quantity']);}if(!empty($v['stock_status']))$p->set_stock_status(in_array(strtolower($v['stock_status']),['outofstock','onbackorder'],true)?strtolower($v['stock_status']):'instock');if(!empty($v['stock_status'])&&strtolower((string)$v['stock_status'])==='yes')$p->set_stock_status('instock');}
 private function find_meta_product($f,$v){$x=get_posts(['post_type'=>'product','post_status'=>'any','posts_per_page'=>1,'meta_key'=>'_'.sanitize_key($f),'meta_value'=>$v,'fields'=>'ids']);return $x?(int)$x[0]:0;}
 private function taxonomy($n){$t='pa_'.sanitize_title($n);if(!taxonomy_exists($t))register_taxonomy($t,'product',['public'=>false,'show_ui'=>false,'rewrite'=>false]);return $t;}
 private function apply_attributes($id,$n,$a){foreach((array)$a as $name=>$s){$v=$this->value($n,$s);if($v!=='')wp_set_object_terms($id,array_filter(array_map('trim',explode('|',$v))),$this->taxonomy($name),false);}}
 private function variation_attributes($n,$a){$o=[];foreach((array)$a as $name=>$s){$v=$this->value($n,$s);if($v!=='')$o[$this->taxonomy($name)]=['name'=>$this->taxonomy($name),'value'=>$v,'is_visible'=>1,'is_variation'=>1,'is_taxonomy'=>1];}return $o;}
 private function save_variation($parent,$n,$f){$v=$this->values($n,$f['map']??[]);$field=$f['variation_identifier_field']??'sku';$id=trim((string)($v[$field]??($v['sku']??'')));if(!$id)return false;$vid=wc_get_product_id_by_sku($id);$p=$vid?wc_get_product($vid):new WC_Product_Variation();$p->set_parent_id($parent);$p->set_sku($id);if(isset($v['price'])&&$v['price']!==''){$x=(string)(float)$v['price'];$p->set_regular_price($x);$p->set_price($x);}if(isset($v['sale_price'])&&$v['sale_price']!=='')$p->set_sale_price((string)(float)$v['sale_price']);if(isset($v['stock_quantity'])&&$v['stock_quantity']!==''){$p->set_manage_stock(true);$p->set_stock_quantity((int)$v['stock_quantity']);}$attrs=[];foreach((array)($f['attributes']??[]) as $name=>$s){$x=$this->value($n,$s);if($x!=='')$attrs['pa_'.sanitize_title($name)]=sanitize_title($x);}$p->set_attributes($attrs);$p->save();return true;}
}
