<?php
if (!defined('ABSPATH')) exit;

final class WPFI_Admin {
    private $repo; private $scheduler; private $importer; private $logger;
    public function __construct($repo,$scheduler,$importer,$logger) { $this->repo=$repo;$this->scheduler=$scheduler;$this->importer=$importer;$this->logger=$logger; add_action('admin_menu',[$this,'menu']); add_action('admin_post_wpfi_save_feed',[$this,'save']); add_action('admin_post_wpfi_delete_feed',[$this,'delete']); add_action('admin_post_wpfi_run_feed',[$this,'run']); add_action('admin_post_wpfi_clear_logs',[$this,'clear_logs']); }
    public function menu() { add_submenu_page('woocommerce','XML Feed Importer','XML Feed Importer','manage_woocommerce','wpfi-feeds',[$this,'page']); }
    private function can() { return current_user_can('manage_woocommerce'); }
    private function url($args=[]) { return add_query_arg(array_merge(['page'=>'wpfi-feeds'],$args),admin_url('admin.php')); }
    private function notice() { if (!empty($_GET['message'])) echo '<div class="notice notice-success is-dismissible"><p>'.esc_html(sanitize_text_field(wp_unslash($_GET['message']))).'</p></div>'; }
    public function page() { if(!$this->can()) return; $action=sanitize_key($_GET['action']??'list'); $this->notice(); if($action==='edit'||$action==='new') $this->edit_page(); elseif($action==='logs') $this->logs_page(); else $this->list_page(); }
    private function list_page() { $feeds=$this->repo->all(); ?><div class="wrap"><h1 class="wp-heading-inline">XML Product Feeds</h1> <a class="page-title-action" href="<?php echo esc_url($this->url(['action'=>'new'])); ?>">Add feed</a> <a class="page-title-action" href="<?php echo esc_url($this->url(['action'=>'logs'])); ?>">View import logs</a><hr class="wp-header-end"><table class="widefat striped"><thead><tr><th>Name</th><th>URL</th><th>Frequency</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php if(!$feeds): ?><tr><td colspan="5">No feeds configured.</td></tr><?php else: foreach($feeds as $feed): ?><tr><td><strong><?php echo esc_html($feed['name']); ?></strong><br><code><?php echo esc_html($feed['slug']); ?></code></td><td><a href="<?php echo esc_url($feed['url']); ?>" target="_blank" rel="noopener"><?php echo esc_html($feed['url']); ?></a></td><td><?php echo esc_html($feed['frequency']); ?></td><td><?php echo !empty($feed['enabled'])?'Enabled':'Disabled'; ?></td><td><a href="<?php echo esc_url($this->url(['action'=>'edit','id'=>$feed['id']])); ?>">Edit</a> | <a href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=wpfi_run_feed&id='.$feed['id']),'wpfi_run_'.$feed['id'])); ?>">Run now</a> | <a href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=wpfi_delete_feed&id='.$feed['id']),'wpfi_delete_'.$feed['id'])); ?>" onclick="return confirm('Delete this feed?')">Delete</a></td></tr><?php endforeach; endif; ?></tbody></table></div><?php }
    private function field($name,$value,$type='text') { return '<input type="'.$type.'" name="'.$name.'" value="'.esc_attr($value??'').'" class="regular-text" />'; }
    private function edit_page() { $id=sanitize_text_field($_GET['id']??''); $f=wp_parse_args($id?$this->repo->get($id):[], $this->repo->defaults()); ?><div class="wrap"><h1><?php echo $id?'Edit feed':'Add feed'; ?></h1><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="wpfi_save_feed"><input type="hidden" name="id" value="<?php echo esc_attr($f['id']); ?>"><?php wp_nonce_field('wpfi_save_feed'); ?><table class="form-table"><tr><th>Name</th><td><?php echo $this->field('name',$f['name']); ?></td></tr><tr><th>Slug</th><td><?php echo $this->field('slug',$f['slug']); ?></td></tr><tr><th>XML URL</th><td><?php echo $this->field('url',$f['url'],'url'); ?></td></tr><tr><th>Enabled</th><td><input type="checkbox" name="enabled" value="1" <?php checked($f['enabled']); ?>></td></tr><tr><th>Frequency</th><td><select name="frequency"><?php foreach(['wpfi_15m'=>'Every 15 minutes','wpfi_30m'=>'Every 30 minutes','hourly'=>'Hourly','twicedaily'=>'Twice daily','daily'=>'Daily','wpfi_6h'=>'Every 6 hours','weekly'=>'Weekly'] as $key=>$label): ?><option value="<?php echo esc_attr($key); ?>" <?php selected($f['frequency'],$key); ?>><?php echo esc_html($label); ?></option><?php endforeach; ?></select></td></tr><tr><th>Product XPath</th><td><?php echo $this->field('product_xpath',$f['product_xpath']); ?></td></tr><tr><th>Identifier field</th><td><?php echo $this->field('identifier_field',$f['identifier_field']); ?></td></tr><tr><th>Variation XPath</th><td><?php echo $this->field('variation_xpath',$f['variation_xpath']); ?><p class="description">Leave blank for simple products.</p></td></tr><tr><th>Variation identifier</th><td><?php echo $this->field('variation_identifier_field',$f['variation_identifier_field']); ?></td></tr></table><h2>Mappings</h2><p>One mapping per line: <code>WooCommerce field=XML selector</code></p><textarea name="map" rows="8" class="large-text code"><?php echo esc_textarea($this->pairs($f['map'])); ?></textarea><h2>Custom attributes</h2><p>One attribute per line: <code>Attribute name=XML selector</code>. Separate multiple values with <code>|</code>.</p><textarea name="attributes" rows="5" class="large-text code"><?php echo esc_textarea($this->pairs($f['attributes'])); ?></textarea><h2>Namespaces</h2><p>One namespace per line: <code>prefix=URI</code>.</p><textarea name="namespaces" rows="5" class="large-text code"><?php echo esc_textarea($this->pairs($f['namespaces'])); ?></textarea><p><button class="button button-primary">Save feed</button> <a class="button" href="<?php echo esc_url($this->url()); ?>">Cancel</a></p></form></div><?php }
    private function pairs($pairs) { $out=[]; foreach((array)$pairs as $key=>$value)$out[]=$key.'='.$value; return implode("\n",$out); }
    private function parse_pairs($text) { $out=[]; foreach(preg_split('/\r\n|\r|\n/',(string)$text) as $line){$parts=explode('=', $line, 2); if(count($parts)===2 && trim($parts[0]) && trim($parts[1]))$out[sanitize_text_field(trim($parts[0]))]=sanitize_text_field(trim($parts[1]));} return $out; }
    public function save() { if(!$this->can()||!check_admin_referer('wpfi_save_feed'))wp_die('Permission denied.'); $f=$this->repo->defaults(); $f['id']=sanitize_text_field($_POST['id']??'')?:wp_generate_uuid4(); foreach(['name','slug','product_xpath','identifier_field','variation_xpath','variation_identifier_field'] as $key)$f[$key]=sanitize_text_field(wp_unslash($_POST[$key]??'')); $f['url']=esc_url_raw(wp_unslash($_POST['url']??'')); $f['enabled']=!empty($_POST['enabled'])?1:0; $f['frequency']=sanitize_key($_POST['frequency']??'daily'); foreach(['map','attributes','namespaces'] as $key)$f[$key]=$this->parse_pairs(wp_unslash($_POST[$key]??'')); if(!$f['name']||!$f['slug']||!$f['url'])wp_die('Name, slug, and URL are required.'); $this->repo->save($f); $this->scheduler->sync(); wp_safe_redirect($this->url(['message'=>'Feed saved.'])); exit; }
    public function delete() { $id=sanitize_text_field($_GET['id']??''); if(!$this->can()||!$id||!check_admin_referer('wpfi_delete_'.$id))wp_die('Permission denied.'); $this->repo->delete($id); $this->scheduler->sync(); wp_safe_redirect($this->url(['message'=>'Feed deleted.'])); exit; }
    public function run() { $id=sanitize_text_field($_GET['id']??''); if(!$this->can()||!$id||!check_admin_referer('wpfi_run_'.$id))wp_die('Permission denied.'); $feed=$this->repo->get($id); if($feed)$this->importer->import($feed); wp_safe_redirect($this->url(['message'=>'Feed import completed.'])); exit; }
    private function logs_page() { ?><div class="wrap"><h1>XML Feed Import Logs</h1><p><a href="<?php echo esc_url($this->url()); ?>">Back to feeds</a></p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="wpfi_clear_logs"><?php wp_nonce_field('wpfi_clear_logs'); ?><button class="button" onclick="return confirm('Clear all logs?')">Clear logs</button></form><table class="widefat striped" style="margin-top:15px"><thead><tr><th>Time</th><th>Feed</th><th>Level</th><th>Message</th></tr></thead><tbody><?php foreach($this->logger->all() as $log): ?><tr><td><?php echo esc_html($log['time']??''); ?></td><td><?php echo esc_html($log['feed']??''); ?></td><td><?php echo esc_html($log['level']??''); ?></td><td><?php echo esc_html($log['message']??''); ?></td></tr><?php endforeach; ?></tbody></table></div><?php }
    public function clear_logs() { if(!$this->can()||!check_admin_referer('wpfi_clear_logs'))wp_die('Permission denied.'); $this->logger->clear(); wp_safe_redirect($this->url(['action'=>'logs','message'=>'Logs cleared.'])); exit; }
}
