<?php
if (!defined('ABSPATH')) exit;
final class WPFI_Importer {
 private $logger; public function __construct($logger){$this->logger=$logger;}
 public function import(array $feed){ if (($feed['format']??'xml')==='csv') return $this->import_csv($feed); return $this->import_xml($feed); }
 private function request($feed){$url=$this->authenticated_url($feed);$r=wp_remote_get($url,['timeout'=>120,'redirection'=>3,'user-agent'=>'WPFI/'.WPFI_VERSION,'headers'=>$this->auth_headers($feed)]);if(is_wp_error($r)){$this->logger->write($feed,'error','Request failed: '.$r->get_error_message());return false;}if(wp_remote_retrieve_response_code($r)!==200){$this->logger->write($feed,'error','Request failed with HTTP '.wp_remote_retrieve_response_code($r));return false;}return wp_remote_retrieve_body($r);}
 private function import_csv($feed){$body=$this->request($feed);if($body===false)return false;$cfg=wp_parse_args($feed['csv']??[],['delimiter'=>',','enclosure'=>'"','has_header'=>1,'encoding'=>'UTF-8']);$rows=$this->csv_rows($body,$cfg);if(!$rows){$this->logger->write($feed,'error','No CSV rows returned.');return false;}$saved=0;foreach($rows as $row){$values=[];foreach($row as $key=>$value){$values[$key]=trim((string)$value);}if(!$this->save_product($feed,$values)){$this->logger->write($feed,'warning','Skipped invalid row.');continue;}$saved++;}$this->logger->write($feed,'info','Imported '.$saved.' products.');return true;}
 private function import_xml($feed){$body=$this->request($feed);if($body===false)return false;libxml_use_internal_errors(true);$xml=simplexml_load_string($body,'SimpleXMLElement',LIBXML_NOCDATA);if($xml===false){$this->logger->write($feed,'error','Unable to parse XML feed.');return false;} $root=$feed['product_xpath']??'/products/product';$nodes=$xml->xpath($root);if(!$nodes){$this->logger->write($feed,'error','No product nodes matched XPath: '.$root);return false;} $saved=0; foreach($nodes as $node){ $values=$this->values($node,$feed['map']??[]); $field=$feed['identifier_field']??'sku'; $id=trim((string)($values[$field]??($values['sku']??''))); if($id===''){ $this->logger->write($feed,'warning','Skipped product without identifier: '.($field?:'sku')); continue; } if($this->save_product($feed,$values,$node)){ $saved++; } } $this->logger->write($feed,'info','Imported '.$saved.' products.'); return true; }
 private function save_product($feed,$values,$node=null){$field=$feed['identifier_field']??'sku';$id=trim((string)($values[$field]??($values['sku']??'')));if(!$id){$this->logger->write($feed,'warning','Missing product identifier for feed: '.print_r($values,true));return false;}$product_id=$this->find_product_by_identifier($feed,$id);$data=['name'=>$values['name']??$id,'sku'=>$id,'description'=>($values['description']??'')];if(isset($values['short_description']))$data['short_description']=$values['short_description'];if(isset($values['price']))$data['price']=$values['price'];if(isset($values['sale_price']))$data['sale_price']=$values['sale_price'];if(isset($values['stock_quantity']))$data['stock_quantity']=$values['stock_quantity'];if(isset($values['stock_status']))$data['stock_status']=$values['stock_status'];if(isset($values['category']))$data['category']=$values['category'];if(isset($values['image']))$data['image']=$values['image'];if($product_id){$this->update_product($product_id,$data);return true;}$product_id=$this->create_product($data);if($product_id){$this->save_identifier_meta($feed,$id,$product_id);return true;}return false;}
 private function save_variation($parent_values,$node,$feed){$values=$this->values($node,$feed['map']??[]);$field=$feed['variation_identifier_field']??'sku';$id=trim((string)($values[$field]??($values['sku']??'')));if(!$id){return false;}$product_id=$this->find_product_by_identifier($feed,$id,true);$data=['name'=>$values['name']??$id,'sku'=>$id,'description'=>$values['description']??''];if(isset($values['price']))$data['price']=$values['price'];if(isset($values['sale_price']))$data['sale_price']=$values['sale_price'];if(isset($values['stock_quantity']))$data['stock_quantity']=$values['stock_quantity'];if(isset($values['stock_status']))$data['stock_status']=$values['stock_status'];if(isset($values['image']))$data['image']=$values['image'];if($product_id){$this->update_variation($product_id,$data);return true;}$this->logger->write($feed,'warning','Variation not created: '.$id);return false;}
 private function values($node,$map){$v=[];foreach((array)$map as $k=>$s)$v[$k]=$this->value($node,$s);return $v;}
 private function value($node,$s){if(!$s)return '';if(strpos($s,'/')!==false||strpos($s,'@')!==false||strpos($s,'[')!==false){$r=$node->xpath($s);return is_array($r)?trim((string)($r[0]??'')):'';}return trim((string)$node->{$s});}
 private function apply_values($p,$v,$id){$p->set_name($v['name']??$id);$p->set_sku($id);if(isset($v['description']))$p->set_description(wp_kses_post($v['description']));if(isset($v['short_description']))$p->set_short_description(wp_kses_post($v['short_description']));if(isset($v['price']))$p->set_regular_price((string)$v['price']);if(isset($v['sale_price']))$p->set_sale_price((string)$v['sale_price']);if(isset($v['stock_quantity']))$p->set_stock_quantity((string)$v['stock_quantity']);if(isset($v['stock_status']))$p->set_stock_status($v['stock_status']);if(isset($v['category']))$p->set_category_ids($this->ensure_categories($v['category']));if(isset($v['image']))$this->image($p->get_id(),$v['image']);}
 private function find_meta_product($f,$v){$x=get_posts(['post_type'=>'product','post_status'=>'any','posts_per_page'=>1,'meta_key'=>'_'.sanitize_key($f),'meta_value'=>$v,'fields'=>'ids']);return $x[0]??0;}
 private function taxonomy($n){$t='pa_'.sanitize_title($n);if(!taxonomy_exists($t))register_taxonomy($t,'product',['public'=>false,'show_ui'=>false,'rewrite'=>false]);return $t;}
 private function apply_attributes($id,$n,$a){foreach((array)$a as $name=>$s){$v=$this->value($n,$s);if($v!=='')wp_set_object_terms($id,array_filter(array_map('trim',explode('|',$v))),$this->taxonomy($name));}}
 private function apply_csv_attributes($id,$values,$a){foreach((array)$a as $name=>$column){$v=$values[$column]??'';if($v!=='')wp_set_object_terms($id,array_filter(array_map('trim',explode('|',$v))),$this->taxonomy($name));}}
 private function image($id,$url){if(!is_string($url)||$url==='')return;require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/image.php';$attachment_id=attachment_url_to_postid($url);if(!$attachment_id){$tmp=download_url($url);if(is_wp_error($tmp))return;try{ $file=wp_upload_bits(basename(parse_url($url,PHP_URL_PATH)),null,file_get_contents($tmp)); if($file['error']){ @unlink($tmp); return; } $attachment_id=media_sideload_image($url,$id,'', 'id'); }catch(
Throwable $e){ @unlink($tmp); return; } @unlink($tmp); } if($attachment_id){ update_post_meta($id,'_thumbnail_id',$attachment_id); }}
 private function authenticated_url($feed){$a=$feed['auth']??[];$url=trim((string)($feed['url']??''));$params=is_array($a['query_params']??null)?$a['query_params']:[];$path_params=is_array($a['path_params']??null)?$a['path_params']:[];$template=trim((string)($a['path_template']??''));if($template!==''){$url=$template;}if(!empty($path_params)){$url=rtrim($url,'/');foreach($path_params as $key=>$value){$placeholder='{'.$key.'}';if(strpos($url,$placeholder)!==false){$url=str_replace($placeholder,rawurlencode((string)$value),$url);continue;}if(strpos($url,'/{'.$key.'}')!==false){$url=str_replace('/{'.$key.'}','/'.rawurlencode((string)$value),$url);continue;}$url.='/'.rawurlencode((string)$key).'/'.rawurlencode((string)$value);}}return $params?add_query_arg(array_map('strval',$params),$url):$url;}
 private function auth_headers($feed){$a=$feed['auth']??[];$h=[];$type=$a['type']??'none';if($type==='api_key'&&!empty($a['api_key']))$h[$a['api_key_name']??'X-API-Key']=$a['api_key'];if($type==='basic'&&!empty($a['username'])&&!empty($a['password']))$h['Authorization']='Basic '.base64_encode($a['username'].':'.$a['password']);if($type==='bearer'&&!empty($a['token']))$h['Authorization']='Bearer '.$a['token'];if($type==='custom'&&!empty($a['header_name'])&&!empty($a['header_value']))$h[$a['header_name']]=$a['header_value'];return $h;}
 private function csv_rows($body,$cfg){$encoding=$cfg['encoding']??'UTF-8';$body=$this->convert_encoding($body,$encoding);$lines=preg_split('/\r\n|\r|\n/',$body);if(!$lines)return[];$rows=[];$header=null;foreach($lines as $line){if(trim($line)==='')continue;$cols=str_getcsv($line,$cfg['delimiter']??',',$cfg['enclosure']??'"');if($header===null){$header=$cols;continue;}$rows[] = array_combine($header,$cols);}return $rows;}
 private function convert_encoding($body,$encoding){if(strtoupper((string)$encoding)==='UTF-8'||$body==='')return $body;return mb_convert_encoding($body,'UTF-8',$encoding);} 
 private function create_product($data){ $post = ['post_title' => $data['name'], 'post_status' => 'publish', 'post_type' => 'product' ]; $id = wp_insert_post($post); if ($id && $id > 0) { update_post_meta($id, '_sku', sanitize_text_field($data['sku'])); if (!empty($data['price'])) update_post_meta($id, '_regular_price', (string)$data['price']); if (!empty($data['sale_price'])) update_post_meta($id, '_sale_price', (string)$data['sale_price']); if (!empty($data['stock_quantity'])) update_post_meta($id, '_stock', (string)$data['stock_quantity']); if (!empty($data['stock_status'])) update_post_meta($id, '_stock_status', sanitize_text_field($data['stock_status'])); if (!empty($data['category'])) wp_set_object_terms($id, array_filter(array_map('trim', explode('|', (string)$data['category']))), 'product_cat', true); if (!empty($data['image'])) $this->image($id, $data['image']); return $id; } return 0; }
 private function update_product($id, $data){ if (!empty($data['name'])) wp_update_post(['ID' => $id, 'post_title' => $data['name']]); if (!empty($data['sku'])) update_post_meta($id, '_sku', sanitize_text_field($data['sku'])); if (array_key_exists('price',$data) && $data['price'] !== '') update_post_meta($id, '_regular_price', (string)$data['price']); if (array_key_exists('sale_price',$data) && $data['sale_price'] !== '') update_post_meta($id, '_sale_price', (string)$data['sale_price']); if (array_key_exists('stock_quantity',$data) && $data['stock_quantity'] !== '') update_post_meta($id, '_stock', (string)$data['stock_quantity']); if (array_key_exists('stock_status',$data) && $data['stock_status'] !== '') update_post_meta($id, '_stock_status', sanitize_text_field($data['stock_status'])); if (array_key_exists('category',$data) && $data['category'] !== '') wp_set_object_terms($id, array_filter(array_map('trim', explode('|', (string)$data['category']))), 'product_cat', true); if (array_key_exists('image',$data) && $data['image'] !== '') $this->image($id, $data['image']); return true; }
 private function update_variation($id, $data){ return $this->update_product($id, $data); }
 private function find_product_by_identifier($feed,$id,$variation=false){ return $this->find_meta_product(($variation ? 'variation_' : '').$feed['identifier_field']??'sku', $id); }
 private function save_identifier_meta($feed,$id,$product_id){ $key='_' . sanitize_key(($feed['identifier_field']??'sku')); update_post_meta($product_id, $key, sanitize_text_field($id)); }
}
